// Load disposable domains from the data file
export const disposableDomains = new Set([
  "10minutemail.com",
  "20minutemail.com",
  "guerrillamail.com",
  "mailinator.com",
  "tempmail.org",
  "yopmail.com",
  "throwaway.email",
  "temp-mail.org",
  "maildrop.cc",
  "sharklasers.com",
  "guerrillamailblock.com",
  "pokemail.net",
  "spam4.me",
  "bccto.me",
  "chacuo.net",
  "dispostable.com",
  "fakeinbox.com",
  "getnada.com",
  "harakirimail.com",
  "incognitomail.org",
  "jetable.org",
  "koszmail.pl",
  "kurzepost.de",
  "lifebyfood.com",
  "lroid.com",
  "mytrashmail.com",
  "no-spam.ws",
  "nowmymail.com",
  "objectmail.com",
  "proxymail.eu",
  "rcpt.at",
  "safe-mail.net",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "tempemail.com",
  "tempmailaddress.com",
  "tempymail.com",
  "thankyou2010.com",
  "trash-mail.at",
  "trashmail.at",
  "trashmail.me",
  "trashmail.net",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wh4f.org",
])

export function isDisposableDomain(domain: string): boolean {
  return disposableDomains.has(domain.toLowerCase())
}
